/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'portfolioId' : IDL.Nat,
  'peRatio' : IDL.Opt(IDL.Float64),
  'currentPrice' : IDL.Float64,
  'ticker' : IDL.Text,
  'targetAllocationPct' : IDL.Float64,
  'marketCap' : IDL.Opt(IDL.Float64),
  'beta' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'sector' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
  'assetType' : IDL.Text,
  'dividendYield' : IDL.Opt(IDL.Float64),
  'avgBuyPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AssetBreakdown = IDL.Record({
  'gainLossPct' : IDL.Float64,
  'asset' : Asset,
  'value' : IDL.Float64,
  'cost' : IDL.Float64,
  'gainLoss' : IDL.Float64,
  'actualAllocationPct' : IDL.Float64,
});
export const PortfolioSummary = IDL.Record({
  'totalGainLossPct' : IDL.Float64,
  'totalMarketValue' : IDL.Float64,
  'assets' : IDL.Vec(AssetBreakdown),
  'totalGainLoss' : IDL.Float64,
  'totalCostBasis' : IDL.Float64,
});
export const Portfolio = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const ProfileRebalanceSuggestion = IDL.Record({
  'suggestedTargetPct' : IDL.Float64,
  'asset' : Asset,
  'rationale' : IDL.Text,
});
export const RebalanceSuggestion = IDL.Record({
  'suggestedAmount' : IDL.Float64,
  'allocationDiffPct' : IDL.Float64,
  'asset' : Asset,
  'targetAllocationPct' : IDL.Float64,
  'currentValue' : IDL.Float64,
  'currentAllocationPct' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAsset' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPortfolio' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deletePortfolio' : IDL.Func([IDL.Nat], [], []),
  'renamePortfolio' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAssets' : IDL.Func([IDL.Nat], [IDL.Vec(Asset)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolioSummary' : IDL.Func([IDL.Nat], [PortfolioSummary], ['query']),
  'getPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], ['query']),
  'getProfileRebalanceSuggestions' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Vec(ProfileRebalanceSuggestion)],
      ['query'],
    ),
  'getRebalanceSuggestions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RebalanceSuggestion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAsset' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAsset' : IDL.Func([Asset], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'portfolioId' : IDL.Nat,
    'peRatio' : IDL.Opt(IDL.Float64),
    'currentPrice' : IDL.Float64,
    'ticker' : IDL.Text,
    'targetAllocationPct' : IDL.Float64,
    'marketCap' : IDL.Opt(IDL.Float64),
    'beta' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'sector' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
    'assetType' : IDL.Text,
    'dividendYield' : IDL.Opt(IDL.Float64),
    'avgBuyPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AssetBreakdown = IDL.Record({
    'gainLossPct' : IDL.Float64,
    'asset' : Asset,
    'value' : IDL.Float64,
    'cost' : IDL.Float64,
    'gainLoss' : IDL.Float64,
    'actualAllocationPct' : IDL.Float64,
  });
  const PortfolioSummary = IDL.Record({
    'totalGainLossPct' : IDL.Float64,
    'totalMarketValue' : IDL.Float64,
    'assets' : IDL.Vec(AssetBreakdown),
    'totalGainLoss' : IDL.Float64,
    'totalCostBasis' : IDL.Float64,
  });
  const Portfolio = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const ProfileRebalanceSuggestion = IDL.Record({
    'suggestedTargetPct' : IDL.Float64,
    'asset' : Asset,
    'rationale' : IDL.Text,
  });
  const RebalanceSuggestion = IDL.Record({
    'suggestedAmount' : IDL.Float64,
    'allocationDiffPct' : IDL.Float64,
    'asset' : Asset,
    'targetAllocationPct' : IDL.Float64,
    'currentValue' : IDL.Float64,
    'currentAllocationPct' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAsset' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPortfolio' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deletePortfolio' : IDL.Func([IDL.Nat], [], []),
  'renamePortfolio' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAssets' : IDL.Func([IDL.Nat], [IDL.Vec(Asset)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolioSummary' : IDL.Func([IDL.Nat], [PortfolioSummary], ['query']),
    'getPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], ['query']),
    'getProfileRebalanceSuggestions' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Vec(ProfileRebalanceSuggestion)],
        ['query'],
      ),
    'getRebalanceSuggestions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RebalanceSuggestion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAsset' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAsset' : IDL.Func([Asset], [], []),
  });
};

export const init = ({ IDL }) => { return []; };