/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : bigint,
  'portfolioId' : bigint,
  'peRatio' : [] | [number],
  'currentPrice' : number,
  'ticker' : string,
  'targetAllocationPct' : number,
  'marketCap' : [] | [number],
  'beta' : [] | [number],
  'name' : string,
  'sector' : [] | [string],
  'notes' : [] | [string],
  'quantity' : number,
  'assetType' : string,
  'dividendYield' : [] | [number],
  'avgBuyPrice' : number,
}
export interface AssetBreakdown {
  'gainLossPct' : number,
  'asset' : Asset,
  'value' : number,
  'cost' : number,
  'gainLoss' : number,
  'actualAllocationPct' : number,
}
export interface Portfolio {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
}
export interface PortfolioSummary {
  'totalGainLossPct' : number,
  'totalMarketValue' : number,
  'assets' : Array<AssetBreakdown>,
  'totalGainLoss' : number,
  'totalCostBasis' : number,
}
export interface ProfileRebalanceSuggestion {
  'suggestedTargetPct' : number,
  'asset' : Asset,
  'rationale' : string,
}
export interface RebalanceSuggestion {
  'suggestedAmount' : number,
  'allocationDiffPct' : number,
  'asset' : Asset,
  'targetAllocationPct' : number,
  'currentValue' : number,
  'currentAllocationPct' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAsset' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      [] | [number],
      [] | [number],
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [string],
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPortfolio' : ActorMethod<[string], bigint>,
  'deletePortfolio' : ActorMethod<[bigint], undefined>,
  'renamePortfolio' : ActorMethod<[bigint, string], undefined>,
  'getAssets' : ActorMethod<[bigint], Array<Asset>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioSummary' : ActorMethod<[bigint], PortfolioSummary>,
  'getPortfolios' : ActorMethod<[], Array<Portfolio>>,
  'getProfileRebalanceSuggestions' : ActorMethod<
    [bigint, string, string],
    Array<ProfileRebalanceSuggestion>
  >,
  'getRebalanceSuggestions' : ActorMethod<[bigint], Array<RebalanceSuggestion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAsset' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAsset' : ActorMethod<[Asset], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];