/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PortfolioSummary {
    totalGainLossPct: number;
    totalMarketValue: number;
    assets: Array<AssetBreakdown>;
    totalGainLoss: number;
    totalCostBasis: number;
}
export interface ProfileRebalanceSuggestion {
    suggestedTargetPct: number;
    asset: Asset;
    rationale: string;
}
export interface Portfolio {
    id: bigint;
    name: string;
    createdAt: bigint;
}
export interface RebalanceSuggestion {
    suggestedAmount: number;
    allocationDiffPct: number;
    asset: Asset;
    targetAllocationPct: number;
    currentValue: number;
    currentAllocationPct: number;
}
export interface Asset {
    id: bigint;
    portfolioId: bigint;
    peRatio?: number;
    currentPrice: number;
    ticker: string;
    targetAllocationPct: number;
    marketCap?: number;
    beta?: number;
    name: string;
    sector?: string;
    notes?: string;
    quantity: number;
    assetType: string;
    dividendYield?: number;
    avgBuyPrice: number;
}
export interface AssetBreakdown {
    gainLossPct: number;
    asset: Asset;
    value: number;
    cost: number;
    gainLoss: number;
    actualAllocationPct: number;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAsset(portfolioId: bigint, ticker: string, name: string, assetType: string, quantity: number, avgBuyPrice: number, currentPrice: number, targetAllocationPct: number, marketCap: number | null, peRatio: number | null, sector: string | null, dividendYield: number | null, beta: number | null, notes: string | null): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPortfolio(name: string): Promise<bigint>;
    deletePortfolio(id: bigint): Promise<void>;
    getAssets(portfolioId: bigint): Promise<Array<Asset>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPortfolioSummary(portfolioId: bigint): Promise<PortfolioSummary>;
    getPortfolios(): Promise<Array<Portfolio>>;
    getProfileRebalanceSuggestions(portfolioId: bigint, marketCondition: string, riskProfile: string): Promise<Array<ProfileRebalanceSuggestion>>;
    getRebalanceSuggestions(portfolioId: bigint): Promise<Array<RebalanceSuggestion>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeAsset(portfolioId: bigint, assetId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAsset(asset: Asset): Promise<void>;
}
import type { Asset as _Asset, AssetBreakdown as _AssetBreakdown, PortfolioSummary as _PortfolioSummary, ProfileRebalanceSuggestion as _ProfileRebalanceSuggestion, RebalanceSuggestion as _RebalanceSuggestion, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAsset(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number | null, arg9: number | null, arg10: string | null, arg11: number | null, arg12: number | null, arg13: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPortfolio(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolio(arg0);
            return result;
        }
    }
    async deletePortfolio(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolio(arg0);
            return result;
        }
    }
    async getAssets(arg0: bigint): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssets(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssets(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSummary(arg0: bigint): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary(arg0);
                return from_candid_PortfolioSummary_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary(arg0);
            return from_candid_PortfolioSummary_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolios(): Promise<Array<Portfolio>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolios();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolios();
            return result;
        }
    }
    async getProfileRebalanceSuggestions(arg0: bigint, arg1: string, arg2: string): Promise<Array<ProfileRebalanceSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileRebalanceSuggestions(arg0, arg1, arg2);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileRebalanceSuggestions(arg0, arg1, arg2);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRebalanceSuggestions(arg0: bigint): Promise<Array<RebalanceSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRebalanceSuggestions(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRebalanceSuggestions(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeAsset(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAsset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAsset(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAsset(arg0: Asset): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(to_candid_Asset_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(to_candid_Asset_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AssetBreakdown_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetBreakdown): AssetBreakdown {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Asset_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioSummary_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioSummary): PortfolioSummary {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileRebalanceSuggestion_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileRebalanceSuggestion): ProfileRebalanceSuggestion {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RebalanceSuggestion_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RebalanceSuggestion): RebalanceSuggestion {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalGainLossPct: number;
    totalMarketValue: number;
    assets: Array<_AssetBreakdown>;
    totalGainLoss: number;
    totalCostBasis: number;
}): {
    totalGainLossPct: number;
    totalMarketValue: number;
    assets: Array<AssetBreakdown>;
    totalGainLoss: number;
    totalCostBasis: number;
} {
    return {
        totalGainLossPct: value.totalGainLossPct,
        totalMarketValue: value.totalMarketValue,
        assets: from_candid_vec_n15(_uploadFile, _downloadFile, value.assets),
        totalGainLoss: value.totalGainLoss,
        totalCostBasis: value.totalCostBasis
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gainLossPct: number;
    asset: _Asset;
    value: number;
    cost: number;
    gainLoss: number;
    actualAllocationPct: number;
}): {
    gainLossPct: number;
    asset: Asset;
    value: number;
    cost: number;
    gainLoss: number;
    actualAllocationPct: number;
} {
    return {
        gainLossPct: value.gainLossPct,
        asset: from_candid_Asset_n6(_uploadFile, _downloadFile, value.asset),
        value: value.value,
        cost: value.cost,
        gainLoss: value.gainLoss,
        actualAllocationPct: value.actualAllocationPct
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suggestedTargetPct: number;
    asset: _Asset;
    rationale: string;
}): {
    suggestedTargetPct: number;
    asset: Asset;
    rationale: string;
} {
    return {
        suggestedTargetPct: value.suggestedTargetPct,
        asset: from_candid_Asset_n6(_uploadFile, _downloadFile, value.asset),
        rationale: value.rationale
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suggestedAmount: number;
    allocationDiffPct: number;
    asset: _Asset;
    targetAllocationPct: number;
    currentValue: number;
    currentAllocationPct: number;
}): {
    suggestedAmount: number;
    allocationDiffPct: number;
    asset: Asset;
    targetAllocationPct: number;
    currentValue: number;
    currentAllocationPct: number;
} {
    return {
        suggestedAmount: value.suggestedAmount,
        allocationDiffPct: value.allocationDiffPct,
        asset: from_candid_Asset_n6(_uploadFile, _downloadFile, value.asset),
        targetAllocationPct: value.targetAllocationPct,
        currentValue: value.currentValue,
        currentAllocationPct: value.currentAllocationPct
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    portfolioId: bigint;
    peRatio: [] | [number];
    currentPrice: number;
    ticker: string;
    targetAllocationPct: number;
    marketCap: [] | [number];
    beta: [] | [number];
    name: string;
    sector: [] | [string];
    notes: [] | [string];
    quantity: number;
    assetType: string;
    dividendYield: [] | [number];
    avgBuyPrice: number;
}): {
    id: bigint;
    portfolioId: bigint;
    peRatio?: number;
    currentPrice: number;
    ticker: string;
    targetAllocationPct: number;
    marketCap?: number;
    beta?: number;
    name: string;
    sector?: string;
    notes?: string;
    quantity: number;
    assetType: string;
    dividendYield?: number;
    avgBuyPrice: number;
} {
    return {
        id: value.id,
        portfolioId: value.portfolioId,
        peRatio: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.peRatio)),
        currentPrice: value.currentPrice,
        ticker: value.ticker,
        targetAllocationPct: value.targetAllocationPct,
        marketCap: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.marketCap)),
        beta: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.beta)),
        name: value.name,
        sector: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.sector)),
        notes: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity,
        assetType: value.assetType,
        dividendYield: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.dividendYield)),
        avgBuyPrice: value.avgBuyPrice
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetBreakdown>): Array<AssetBreakdown> {
    return value.map((x)=>from_candid_AssetBreakdown_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProfileRebalanceSuggestion>): Array<ProfileRebalanceSuggestion> {
    return value.map((x)=>from_candid_ProfileRebalanceSuggestion_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RebalanceSuggestion>): Array<RebalanceSuggestion> {
    return value.map((x)=>from_candid_RebalanceSuggestion_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Asset_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Asset): _Asset {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    portfolioId: bigint;
    peRatio?: number;
    currentPrice: number;
    ticker: string;
    targetAllocationPct: number;
    marketCap?: number;
    beta?: number;
    name: string;
    sector?: string;
    notes?: string;
    quantity: number;
    assetType: string;
    dividendYield?: number;
    avgBuyPrice: number;
}): {
    id: bigint;
    portfolioId: bigint;
    peRatio: [] | [number];
    currentPrice: number;
    ticker: string;
    targetAllocationPct: number;
    marketCap: [] | [number];
    beta: [] | [number];
    name: string;
    sector: [] | [string];
    notes: [] | [string];
    quantity: number;
    assetType: string;
    dividendYield: [] | [number];
    avgBuyPrice: number;
} {
    return {
        id: value.id,
        portfolioId: value.portfolioId,
        peRatio: value.peRatio ? candid_some(value.peRatio) : candid_none(),
        currentPrice: value.currentPrice,
        ticker: value.ticker,
        targetAllocationPct: value.targetAllocationPct,
        marketCap: value.marketCap ? candid_some(value.marketCap) : candid_none(),
        beta: value.beta ? candid_some(value.beta) : candid_none(),
        name: value.name,
        sector: value.sector ? candid_some(value.sector) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        quantity: value.quantity,
        assetType: value.assetType,
        dividendYield: value.dividendYield ? candid_some(value.dividendYield) : candid_none(),
        avgBuyPrice: value.avgBuyPrice
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
